const questionSetPrompt = [
    "What is your stature like (body)?",
    "Do you experience cracked skin?",
    "Do you have a high tendency of feeling cold and shivering?",
    "Do you often feel cold and stiff?",
    "Do you have prominent tendons and veins?",
    "How is your sense of touch (Dry/very dry)?",
    "Is your voice dry?",
    "Is your voice low?",
    "Is your voice broken?",
    "Do you experience obstructed voice?",
    "Is your voice hoarse?",
    "Are you a very light sleeper?",
    "Are your movements quick and hurried?",
    "Are you a poor eater?",
    "Is your intake inconsistent?",
    "Do you feel a pulse wave near your thumb?",
    "Does your pulse wave feel like snake movements?",
    "Do you have poor stability in your joints?",
    "Do your joints make cracking movements?",
    "Do you have restless eyes?",
    "Do your eyebrows tend to be restless?",
    "Do you experience restlessness in your jaws, lips, and tongue?",
    "Does restlessness extend to your head and shoulders?",
    "Are your hands often restless?",
    "Do you experience restlessness in your legs?",
    "Are you talkative?",
    "Are you highly talkative?",
    "Are you highly irritable?",
    "Do you have poor stress tolerance?",
    "Are you quick to like things?",
    "Are you quick to dislike things?",
    "Do you easily understand what is heard?",
    "Do you tend to forget quickly?",
    "Do you have intolerance for cold?",
    "Are you quick to take initiative?",
    "Do you experience quick onset of diseases?",
    "Do you have rough nails?",
    "Do you have rough teeth?",
    "Is your mouth rough?",
    "Do you have rough palm/sole?",
    "Is your hair rough?",
    "Is your body hair rough?",
    "Is your facial hair rough?",
    "Do you have less strength?",
    "Does your skin have a yellow tinge?",
    "Is your body delicate?",
    "Is your skin clear?",
    "Do you experience early wrinkling?",
    "Do you have excessive red skin?",
    "Do you have excessive freckles?",
    "Do you have excessive black moles?",
    "Do you often get pimples/boils?",
    "Are your muscles soft?",
    "Do you have lax muscles?",
    "Are you a moderately deep sleeper?",
    "Are you a voracious eater?",
    "Do you have excessive thirst?",
    "Do you consume high amounts of fluids?",
    "Do you have a strong appetite?",
    "Do you have strong digestive power?",
    "Do you sweat profusely?",
    "Does your sweat have a strong odor?",
    "Do you have soft joints?",
    "Do you have loose joints?",
    "Are you a hostile debater?",
    "Do you recover from anger quickly?",
    "Do you possess moderate spiritual knowledge?",
    "Do you have moderate materialistic knowledge?",
    "Do you have intolerance for hot weather?",
    "Are you very aggressive?",
    "Is your stress tolerance low?",
    "Do you have copper nails?",
    "Is your mouth warm?",
    "Do you have bad breath?",
    "Do you have copper palms?",
    "Do you have coppery soles?",
    "Do you have early greying hairs?",
    "Do you have early balding hairs?",
    "Is your hair soft?",
    "Do you have less hair?",
    "Is your hair brown?",
    "Is your body hair soft?",
    "Do you have less body hair?",
    "Is your body hair brown?",
    "Is your facial hair soft?",
    "Do you have less facial hair?",
    "Is your facial hair brown?",
    "Do you emit a foul odor from your head and body?",
    "Do you possess moderate strength?",
    "Do you have a well-built body?",
    "Do you have a pleasing appearance of your body?",
    "Is your body delicate?",
    "Is your skin clear?",
    "Do you have a cheerful disposition?",
    "Do you have a cheerful facial expression?",
    "Do you have a healthy complexion?",
    "Is your body well-nourished?",
    "Do you have compactness in your body?",
    "Is your body firm?",
    "Is your skin oily?",
    "Is your skin smooth?",
    "Is your skin cool?",
    "Do you have a pleasant voice?",
    "Is there softness in your voice?",
    "Are you a very deep sleeper?",
    "Are your movements slow?",
    "Are your movements measured?",
    "Do you take firm steps with your entire sole pressing against the earth?",
    "Are you a slow eater?",
    "Do you have less thirst?",
    "Are you a poor eater?",
    "Do you have a sweet tooth?",
    "Are your movements slow?",
    "Do you sweat minimally?",
    "Is your pulse soft?",
    "Do you have strong joints?",
    "Do you have compact joints?",
    "Do you have white eyes?",
    "Do you have reddish angles of your eyes?",
    "Is your irritability low?",
    "Is your temper slow to rise?",
    "Are you generally calm?",
    "Do you comprehend things slowly?",
    "Do you possess excellent knowledge?",
    "Do you have patience?",
    "Do you take initiative slowly?",
    "Do diseases have a slow onset in your case?",
    "Do you have optimum resistance?",
    "Is your stress tolerance high?",
    "Are you a determined adversary?",
    "Do you have firm hairs?",
    "Do you have curly hairs?",
    "Are your hairs blue-black?",
    "Does your voice resemble the roaring of clouds or a lion?",
    "Do you have excellent strength of hairs?",
  ];
  
  export default questionSetPrompt;
  